trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Checkmarx AST@3
  displayName: "Run Checkmarx One Scan"
  inputs:
    CheckmarxService: 'Git-H'
    projectName: 'GitxAzure'
    branchName: '$(System.PullRequest.SourceBranch)'
    tenantName: 'ps_prayash_mishra'
    additionalParams: |
      --debug
      --client-id myclient
      --client-secret 0z4aBQG1E7J6niqtqKr1c9uwBRFqmebs
