trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Azure Pipelines
    steps:
    - task: Application security testing@2025
      inputs:
        projectName: 'Azuredevops'
        enableProxy: false
        enableSastScan: true
        CheckmarxService: 'Sast Connection'
        enableSastBranching: false
        incScan: false
        generatePDFReport: true
        enableDependencyScan: false